# Generated by Django 5.1.7 on 2025-04-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_like_time_alter_blog_snippet_alter_comment_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
